// <auto-generated />
namespace Blog_Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class add_source : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_source));
        
        string IMigrationMetadata.Id
        {
            get { return "202301111439512_add_source"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
